version: "3"
services:
  hello-world:
    ### local build ###
    build:
      context: .
      dockerfile: Dockerfile
    ### pull image from docker hub ###
    # image: rbocchinfuso/hello-world:latest
    ### required for flask app ###
    ports:
    - 5000:5000
    container_name: hello-world
    restart: unless-stopped
